In [119]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [120]:
#Carga desde un archivo .xlsx sin indice
data = pd.read_excel('Principales_Canales.xlsx', index_col=0)
data.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
NaN,NaN,NaN,Datos erroneos no confiables de Sale-U,NaN,NaN,NaN,-,Sin datos,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ventas X Mes,Ventas Reportadas,12,7,8,13,6,21,17,17,23,...,38,30,41,41,35,37,NaN,NaN,NaN,NaN
Piso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Conversion,NaN,NaN
Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses

In [121]:
###ESTOS CÓDIGOS SON PARA ORDENAR Y LIMPIAR LOS DATOS DE "PISO"###

In [122]:
#Visualizar número de filas
data.iloc[:, 0].head(50)

NaN                                 NaN
NaN                                 NaN
Ventas X Mes          Ventas Reportadas
Piso                                NaN
Piso                        Febrero, 24
Leads                               329
Efectivos                           NaN
SDC                                   -
PDM                                  22
Citas Programadas                     9
Citas Efectivas                       4
Ventas                                9
Conversion                     0.027356
Aporte                              NaN
NaN                                 NaN
NaN                           36.555556
Plazas                              NaN
Plazas                      Febrero, 24
Leads                                 0
Efectivos                           NaN
SDC                                   -
PDM                                   -
Citas Programadas                   NaN
NaN                                 NaN
Citas Efectivas                     NaN
NaN                                 NaN
Ventas                                0
Conversion                            0
Aporte                              NaN
NaN                                 NaN
NaN                                 NaN
Digital                             NaN
Digital                     Febrero, 24
Leads                                57
Efectivos                           NaN
SDC                                   -
PDM                                   -
Citas Programadas                     3
Citas Efectivas                       2
Ventas                              NaN
Conversion                            0
Aporte                              NaN
NaN                                 NaN
NaN                                 NaN
Digital                             NaN
Canal                           Febrero
Leads                                 -
Efectivos                             -
SDC                                   -
PDM                                   -
Name: Unnamed: 1, dtype: object

In [123]:
#Seleccionar datos de Piso
piso = data.iloc[4:14, :]

piso

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses
Leads,329,19,76,87,55,92,77,57,43,50,...,94,105,79,115,85,36,NaN,0.125145,0.089018,0.107199
Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94,105,79,115,84,36,NaN,NaN,NaN,NaN
SDC,-,-,-,-,-,51,32,28,38,32,...,18,24,18,24,22,7,NaN,Aporte,NaN,NaN
PDM,22,13,35,40,28,35,31,28,14,25,...,28,41,36,45,42,16,NaN,Historica,Año actual,Ultimos 3 meses
Citas Programadas,9,28,15,38,78,75,65,37,31,18,...,94,105,12,73,28,11,NaN,0.294222,0.23011,0.240837
Citas Efectivas,4,16,6,16,60,57,46,19,25,14,...,94,105,10,59,25,8,NaN,NaN,NaN,NaN
Ventas,9,4,10,1,3,10,9,6,3,11,...,7,8,9,9,11,2,NaN,Cota (Ventas) Ultimos 6ms,NaN,NaN
Conversion,0.027356,0.210526,0.131579,0.011494,0.054545,0.108696,0.116883,0.105263,0.069767,0.22,...,0.074468,0.07619,0.113924,0.078261,0.129412,0.055556,NaN,Minima,Optima,Maxima
Aporte,NaN,0.333333,1.428571,0.125,0.230769,1.666667,0.428571,0.352941,0.176471,0.478261,...,0.184211,0.266667,0.219512,0.219512,0.314286,0.054054,NaN,6.953455,8.6,10.084523

In [124]:
#Usar la primera fila como nombres de columnas
piso.columns = piso.iloc[0]

#Eliminar la primera fila porque ya se utilizó como encabezado
piso = piso.iloc[1:]

piso

Piso,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses
Leads,329,19,76,87,55,92,77,57,43,50,...,94,105,79,115,85,36,NaN,0.125145,0.089018,0.107199
Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,94,105,79,115,84,36,NaN,NaN,NaN,NaN
SDC,-,-,-,-,-,51,32,28,38,32,...,18,24,18,24,22,7,NaN,Aporte,NaN,NaN
PDM,22,13,35,40,28,35,31,28,14,25,...,28,41,36,45,42,16,NaN,Historica,Año actual,Ultimos 3 meses
Citas Programadas,9,28,15,38,78,75,65,37,31,18,...,94,105,12,73,28,11,NaN,0.294222,0.23011,0.240837
Citas Efectivas,4,16,6,16,60,57,46,19,25,14,...,94,105,10,59,25,8,NaN,NaN,NaN,NaN
Ventas,9,4,10,1,3,10,9,6,3,11,...,7,8,9,9,11,2,NaN,Cota (Ventas) Ultimos 6ms,NaN,NaN
Conversion,0.027356,0.210526,0.131579,0.011494,0.054545,0.108696,0.116883,0.105263,0.069767,0.22,...,0.074468,0.07619,0.113924,0.078261,0.129412,0.055556,NaN,Minima,Optima,Maxima
Aporte,NaN,0.333333,1.428571,0.125,0.230769,1.666667,0.428571,0.352941,0.176471,0.478261,...,0.184211,0.266667,0.219512,0.219512,0.314286,0.054054,NaN,6.953455,8.6,10.084523

In [125]:
#Transponer la tabla
piso = piso.T.reset_index()

#Cambiar nombre de la columna de los meses
piso = piso.rename(columns={"index": "Mes"})

piso

,Piso,Leads,Efectivos,SDC,PDM,Citas Programadas,Citas Efectivas,Ventas,Conversion,Aporte
0,"Febrero, 24",329,NaN,-,22,9,4,9,0.027356,NaN
1,"Marzo, 24",19,NaN,-,13,28,16,4,0.210526,0.333333
2,"Abril, 24",76,NaN,-,35,15,6,10,0.131579,1.428571
3,"Mayo, 24",87,NaN,-,40,38,16,1,0.011494,0.125
4,"Junio, 24",55,NaN,-,28,78,60,3,0.054545,0.230769
5,"Julio, 24",92,NaN,51,35,75,57,10,0.108696,1.666667
6,"Agosto, 24",77,NaN,32,31,65,46,9,0.116883,0.428571
7,"Septiembre, 24",57,NaN,28,28,37,19,6,0.105263,0.352941
8,"Octubre, 24",43,NaN,38,14,31,25,3,0.069767,0.176471
9,"Noviembre, 24",50,NaN,32,25,18,14,11,0.22,0.478261
10,"Diciembre, 24",64,NaN,42,32,42,36,8,0.125,0.363636
11,"Enero, 25",71,71,34,28,71,71,10,0.140845,0.3125
12,"Febrero, 25",64,64,23,33,64,64,11,0.171875,0.423077
13,"Marzo, 25",80,80,28,32,80,80,9,0.1125,0.45
14,"Abril, 25",43,43,13,28,34,34,13,0.302326,0.433333
15,"Mayo, 25",65,65,16,34,65,65,12,0.184615,0.4
16,"Junio, 25",59,59,13,31,59,59,10,0.169492,0.294118
17,"Julio, 25",63,63,12,29,63,63,7,0.111111,0.175
18,"Agosto, 25",71,71,22,44,71,71,7,0.098592,0.194444
19,"Septiembre, 25",58,58,21,31,58,58,7,0.12069,0.259259
20,"Octubre, 25",72,72,24,48,72,72,11,0.152778,0.289474
21,"Noviembre, 25",81,81,21,43,81,81,9,0.111111,0.225
22,"Diciembre, 25",76,76,27,22,76,76,9,0.118421,0.264706
23,"Enero, 26",97,97,27,46,97,97,6,0.061856,0.176471
24,"Febrero, 26",94,94,18,28,94,94,7,0.074468,0.184211
25,"Marzo, 26",105,105,24,41,105,105,8,0.07619,0.266667
26,"Abril, 26",79,79,18,36,12,10,9,0.113924,0.219512
27,"Mayo, 26",115,115,24,45,73,59,9,0.078261,0.219512
28,"Junio, 26",85,84,22,42,28,25,11,0.129412,0.314286
29,"Julio,26",36,36,7,16,11,8,2,0.055556,0.054054
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Historica,0.125145,NaN,Aporte,Historica,0.294222,NaN,Cota (Ventas) Ultimos 6ms,Minima,6.953455
32,Año actual,0.089018,NaN,NaN,Año actual,0.23011,NaN,NaN,Optima,8.6
33,Ultimos 3 meses,0.107199,NaN,NaN,Ultimos 3 meses,0.240837,NaN,NaN,Maxima,10.084523

In [126]:
#Cambiar nombre de la primera columna
piso = piso.rename(columns={piso.columns[0]: "Mes"})

#Quitar el nombre "Piso" que quedó arriba
piso.columns.name = None

piso.head()

,Mes,Leads,Efectivos,SDC,PDM,Citas Programadas,Citas Efectivas,Ventas,Conversion,Aporte
0,"Febrero, 24",329,NaN,-,22,9,4,9,0.027356,NaN
1,"Marzo, 24",19,NaN,-,13,28,16,4,0.210526,0.333333
2,"Abril, 24",76,NaN,-,35,15,6,10,0.131579,1.428571
3,"Mayo, 24",87,NaN,-,40,38,16,1,0.011494,0.125
4,"Junio, 24",55,NaN,-,28,78,60,3,0.054545,0.230769

In [127]:
#Reemplazar guiones por valores nulos
piso = piso.replace("-", np.nan)
piso.head()

,Mes,Leads,Efectivos,SDC,PDM,Citas Programadas,Citas Efectivas,Ventas,Conversion,Aporte
0,"Febrero, 24",329,NaN,NaN,22,9,4,9,0.027356,NaN
1,"Marzo, 24",19,NaN,NaN,13,28,16,4,0.210526,0.333333
2,"Abril, 24",76,NaN,NaN,35,15,6,10,0.131579,1.428571
3,"Mayo, 24",87,NaN,NaN,40,38,16,1,0.011494,0.125
4,"Junio, 24",55,NaN,NaN,28,78,60,3,0.054545,0.230769

In [128]:
#Contar valores nulos por columna
piso.isnull().sum()

Mes                    1
Leads                  1
Efectivos             15
SDC                    8
PDM                    1
Citas Programadas      1
Citas Efectivas        4
Ventas                 3
Conversion             1
Aporte                 2
dtype: int64

In [129]:
#Reemplazar valores nulos por 0
piso = piso.fillna(0)

In [130]:
#Contar valores nulos por columna
piso.isnull().sum()

Mes                   0
Leads                 0
Efectivos             0
SDC                   0
PDM                   0
Citas Programadas     0
Citas Efectivas       0
Ventas                0
Conversion            0
Aporte                0
dtype: int64

In [131]:
###ESTOS CÓDIGOS SON PARA ORDENAR Y LIMPIAR LOS DATOS DE "PLAZAS"###

In [132]:
#Ver filas del archivo original
data.iloc[15:35, 0:5]

                     Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
NaN                   36.555556       4.75        7.6         87  18.333333
Plazas                      NaN        NaN        NaN        NaN        NaN
Plazas              Febrero, 24  Marzo, 24  Abril, 24   Mayo, 24  Junio, 24
Leads                         0          0         25         28         68
Efectivos                   NaN        NaN        NaN        NaN        NaN
SDC                           -          -          -          -          -
PDM                           -          -          1         11          5
Citas Programadas           NaN        NaN          1          3          2
NaN                         NaN        NaN        NaN        NaN        NaN
Citas Efectivas             NaN        NaN        NaN          2          2
NaN                         NaN        NaN        NaN        NaN        NaN
Ventas                        0          0          0          0          0
Conversion                    0          0          0          0          0
Aporte                      NaN          0          0          0          0
NaN                         NaN        NaN        NaN        NaN        NaN
NaN                         NaN        NaN        NaN        NaN        NaN
Digital                     NaN        NaN        NaN        NaN        NaN
Digital             Febrero, 24  Marzo, 24  Abril, 24   Mayo, 24  Junio, 24
Leads                        57        145        129        463        350
Efectivos                   NaN        NaN        NaN        NaN        NaN

In [133]:
#Seleccionar datos de Plazas
plazas = data.iloc[17:29, :]

plazas

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
Plazas,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses
Leads,0,0,25,28,68,294,248,52,59,154,...,433,401,351,352,403,145,NaN,0.02281,0.019441,0.019441
Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,387,364,351,347,403,145,NaN,NaN,NaN,NaN
SDC,-,-,-,-,-,-,-,-,-,-,...,25,26,12,18,16,3,NaN,Aporte,NaN,NaN
PDM,-,-,1,11,5,6,17,8,5,19,...,39,35,30,31,41,12,NaN,Historica,Año actual,Ultimos 3 meses
Citas Programadas,NaN,NaN,1,3,2,30,50,13,13,20,...,105,70,41,68,100,26,NaN,0.21569,0.199146,0.199146
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.242494,0.174564,0.116809,0.193182,0.248139,0.17931,NaN,NaN,NaN,NaN
Citas Efectivas,NaN,NaN,NaN,2,2,8,18,4,6,10,...,82,55,31,49,59,15,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.189376,0.137157,0.088319,0.139205,0.146402,NaN,NaN,NaN,NaN,NaN
Ventas,0,0,0,0,0,2,3,0,2,3,...,6,7,7,7,10,1,NaN,Cota (Ventas) Ultimos 6ms,NaN,NaN
Conversion,0,0,0,0,0,0.006803,0.012097,0,0.033898,0.019481,...,0.013857,0.017456,0.019943,0.019886,0.024814,0.006897,NaN,Minima,Optima,Maxima
Aporte,NaN,0,0,0,0,0.333333,0.142857,0,0.117647,0.130435,...,0.157895,0.233333,0.170732,0.170732,0.285714,0.027027,NaN,5.694707,7.166667,8.638627

In [134]:
#Usar la primera fila como nombres de columnas
plazas.columns = plazas.iloc[0]

#Eliminar la primera fila porque ya se utilizó como encabezado
plazas = plazas.iloc[1:]

plazas

Plazas,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses
Leads,0,0,25,28,68,294,248,52,59,154,...,433,401,351,352,403,145,NaN,0.02281,0.019441,0.019441
Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,387,364,351,347,403,145,NaN,NaN,NaN,NaN
SDC,-,-,-,-,-,-,-,-,-,-,...,25,26,12,18,16,3,NaN,Aporte,NaN,NaN
PDM,-,-,1,11,5,6,17,8,5,19,...,39,35,30,31,41,12,NaN,Historica,Año actual,Ultimos 3 meses
Citas Programadas,NaN,NaN,1,3,2,30,50,13,13,20,...,105,70,41,68,100,26,NaN,0.21569,0.199146,0.199146
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.242494,0.174564,0.116809,0.193182,0.248139,0.17931,NaN,NaN,NaN,NaN
Citas Efectivas,NaN,NaN,NaN,2,2,8,18,4,6,10,...,82,55,31,49,59,15,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.189376,0.137157,0.088319,0.139205,0.146402,NaN,NaN,NaN,NaN,NaN
Ventas,0,0,0,0,0,2,3,0,2,3,...,6,7,7,7,10,1,NaN,Cota (Ventas) Ultimos 6ms,NaN,NaN
Conversion,0,0,0,0,0,0.006803,0.012097,0,0.033898,0.019481,...,0.013857,0.017456,0.019943,0.019886,0.024814,0.006897,NaN,Minima,Optima,Maxima
Aporte,NaN,0,0,0,0,0.333333,0.142857,0,0.117647,0.130435,...,0.157895,0.233333,0.170732,0.170732,0.285714,0.027027,NaN,5.694707,7.166667,8.638627

In [135]:
#Transponer la tabla
plazas = plazas.T.reset_index()

plazas

,Plazas,Leads,Efectivos,SDC,PDM,Citas Programadas,NaN,Citas Efectivas,NaN,Ventas,Conversion,Aporte
0,"Febrero, 24",0,NaN,-,-,NaN,NaN,NaN,NaN,0,0,NaN
1,"Marzo, 24",0,NaN,-,-,NaN,NaN,NaN,NaN,0,0,0
2,"Abril, 24",25,NaN,-,1,1,NaN,NaN,NaN,0,0,0
3,"Mayo, 24",28,NaN,-,11,3,NaN,2,NaN,0,0,0
4,"Junio, 24",68,NaN,-,5,2,NaN,2,NaN,0,0,0
5,"Julio, 24",294,NaN,-,6,30,NaN,8,NaN,2,0.006803,0.333333
6,"Agosto, 24",248,NaN,-,17,50,NaN,18,NaN,3,0.012097,0.142857
7,"Septiembre, 24",52,NaN,-,8,13,NaN,4,NaN,0,0,0
8,"Octubre, 24",59,NaN,-,5,13,NaN,6,NaN,2,0.033898,0.117647
9,"Noviembre, 24",154,NaN,-,19,20,NaN,10,NaN,3,0.019481,0.130435
10,"Diciembre, 24",280,NaN,26,14,40,NaN,19,NaN,7,0.025,0.318182
11,"Enero, 25",172,NaN,22,22,53,NaN,35,NaN,4,0.023256,0.125
12,"Febrero, 25",184,NaN,16,28,48,NaN,36,NaN,1,0.005435,0.038462
13,"Marzo, 25",275,NaN,27,20,35,NaN,28,NaN,3,0.010909,0.15
14,"Abril, 25",301,NaN,19,23,52,NaN,25,NaN,8,0.026578,0.266667
15,"Mayo, 25",275,NaN,23,23,29,NaN,27,NaN,5,0.018182,0.166667
16,"Junio, 25",355,NaN,35,44,90,NaN,61,NaN,13,0.03662,0.382353
17,"Julio, 25",492,NaN,36,37,77,NaN,51,NaN,14,0.028455,0.35
18,"Agosto, 25",397,281,25,30,67,NaN,44,NaN,6,0.015113,0.166667
19,"Septiembre, 25",312,218,44,41,74,NaN,52,NaN,15,0.048077,0.555556
20,"Octubre, 25",324,226,38,43,77,NaN,48,NaN,12,0.037037,0.315789
21,"Noviembre, 25",274,209,31,33,60,NaN,32,NaN,11,0.040146,0.275
22,"Diciembre, 25",325,291,34,18,46,0.141538,41,NaN,9,0.027692,0.264706
23,"Enero, 26",290,261,23,15,23,0.07931,19,0.065517,6,0.02069,0.176471
24,"Febrero, 26",433,387,25,39,105,0.242494,82,0.189376,6,0.013857,0.157895
25,"Marzo, 26",401,364,26,35,70,0.174564,55,0.137157,7,0.017456,0.233333
26,"Abril, 26",351,351,12,30,41,0.116809,31,0.088319,7,0.019943,0.170732
27,"Mayo, 26",352,347,18,31,68,0.193182,49,0.139205,7,0.019886,0.170732
28,"Junio, 26",403,403,16,41,100,0.248139,59,0.146402,10,0.024814,0.285714
29,"Julio,26",145,145,3,12,26,0.17931,15,NaN,1,0.006897,0.027027
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Historica,0.02281,NaN,Aporte,Historica,0.21569,NaN,NaN,NaN,Cota (Ventas) Ultimos 6ms,Minima,5.694707
32,Año actual,0.019441,NaN,NaN,Año actual,0.199146,NaN,NaN,NaN,NaN,Optima,7.166667
33,Ultimos 3 meses,0.019441,NaN,NaN,Ultimos 3 meses,0.199146,NaN,NaN,NaN,NaN,Maxima,8.638627

In [136]:
#Cambiar nombre de la primera columna
plazas = plazas.rename(columns={plazas.columns[0]: "Mes"})

#Quitar el nombre que quedó arriba
plazas.columns.name = None

plazas.head()

,Mes,Leads,Efectivos,SDC,PDM,Citas Programadas,NaN,Citas Efectivas,NaN,Ventas,Conversion,Aporte
0,"Febrero, 24",0,NaN,-,-,NaN,NaN,NaN,NaN,0,0,NaN
1,"Marzo, 24",0,NaN,-,-,NaN,NaN,NaN,NaN,0,0,0
2,"Abril, 24",25,NaN,-,1,1,NaN,NaN,NaN,0,0,0
3,"Mayo, 24",28,NaN,-,11,3,NaN,2,NaN,0,0,0
4,"Junio, 24",68,NaN,-,5,2,NaN,2,NaN,0,0,0

In [137]:
#Reemplazar guiones por valores nulos
plazas = plazas.replace("-", np.nan)

plazas.head()

,Mes,Leads,Efectivos,SDC,PDM,Citas Programadas,NaN,Citas Efectivas,NaN,Ventas,Conversion,Aporte
0,"Febrero, 24",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN
1,"Marzo, 24",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
2,"Abril, 24",25,NaN,NaN,1,1,NaN,NaN,NaN,0,0,0
3,"Mayo, 24",28,NaN,NaN,11,3,NaN,2,NaN,0,0,0
4,"Junio, 24",68,NaN,NaN,5,2,NaN,2,NaN,0,0,0

In [138]:
#Contar valores nulos por columna
plazas.isnull().sum()

Mes                    1
Leads                  1
Efectivos             22
SDC                   13
PDM                    3
Citas Programadas      3
NaN                   26
Citas Efectivas        7
NaN                   28
Ventas                 3
Conversion             1
Aporte                 2
dtype: int64

In [139]:
#Reemplazar valores nulos por 0
plazas = plazas.fillna(0)

In [140]:
#Contar valores nulos por columna
plazas.isnull().sum()

Mes                   0
Leads                 0
Efectivos             0
SDC                   0
PDM                   0
Citas Programadas     0
NaN                   0
Citas Efectivas       0
NaN                   0
Ventas                0
Conversion            0
Aporte                0
dtype: int64

In [141]:
###ESTOS CÓDIGOS SON PARA ORDENAR Y LIMPIAR LOS DATOS DE "DIGITAL"###

In [142]:
#Ver dónde empieza Digital
data.iloc[30:45, 0:5]

                    Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5
NaN                        NaN        NaN        NaN        NaN        NaN
Digital                    NaN        NaN        NaN        NaN        NaN
Digital            Febrero, 24  Marzo, 24  Abril, 24   Mayo, 24  Junio, 24
Leads                       57        145        129        463        350
Efectivos                  NaN        NaN        NaN        NaN        NaN
SDC                          -          -          -          -          -
PDM                          -          -          -          -          -
Citas Programadas            3          6         23         43         43
Citas Efectivas              2          5          5         23         19
Ventas                     NaN          1        NaN        NaN          1
Conversion                   0   0.006897          0          0   0.002857
Aporte                     NaN   0.083333          0          0   0.076923
NaN                        NaN        NaN        NaN        NaN        NaN
NaN                        NaN        NaN        NaN        NaN        NaN
Digital                    NaN        NaN        NaN        NaN        NaN

In [143]:
#Seleccionar datos de Digital
digital = data.iloc[32:42, :]

digital

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34
Digital,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses
Leads,57,145,129,463,350,192,1112,1353,1142,846,...,635,980,834,667,748,298,NaN,0.013748,0.011775,0.010815
Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,457,618,179,170,200,64,NaN,NaN,NaN,NaN
SDC,-,-,-,-,-,-,-,-,-,-,...,21,16,32,30,28,3,NaN,Aporte,NaN,NaN
PDM,-,-,-,-,-,-,-,8,7,17,...,22,25,35,35,28,12,NaN,Historica,Año actual,Ultimos 3 meses
Citas Programadas,3,6,23,43,43,36,57,107,83,71,...,85,78,83,140,101,26,NaN,0.269102,0.249979,0.204878
Citas Efectivas,2,5,5,23,19,14,18,27,33,18,...,43,36,59,103,53,15,NaN,NaN,NaN,NaN
Ventas,NaN,1,NaN,NaN,1,2,NaN,6,1,5,...,13,11,8,9,7,1,NaN,Cota (Ventas) Ultimo Semestre,NaN,NaN
Conversion,0,0.006897,0,0,0.002857,0.010417,0,0.004435,0.000876,0.00591,...,0.020472,0.011224,0.009592,0.013493,0.009358,0.003356,NaN,Minima,Optima,Maxima
Aporte,NaN,0.083333,0,0,0.076923,0.333333,0,0.352941,0.058824,0.217391,...,0.342105,0.366667,0.195122,0.219512,0.2,0.027027,NaN,6.392319,9,11.607681

In [144]:
#Usar la primera fila como nombres de columnas
digital.columns = digital.iloc[0]

#Eliminar la primera fila porque ya se utilizó como encabezado
digital = digital.iloc[1:]

digital

Digital,"Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24",...,"Febrero, 26","Marzo, 26","Abril, 26","Mayo, 26","Junio, 26","Julio,26",NaN,Historica,Año actual,Ultimos 3 meses
Leads,57,145,129,463,350,192,1112,1353,1142,846,...,635,980,834,667,748,298,NaN,0.013748,0.011775,0.010815
Efectivos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,457,618,179,170,200,64,NaN,NaN,NaN,NaN
SDC,-,-,-,-,-,-,-,-,-,-,...,21,16,32,30,28,3,NaN,Aporte,NaN,NaN
PDM,-,-,-,-,-,-,-,8,7,17,...,22,25,35,35,28,12,NaN,Historica,Año actual,Ultimos 3 meses
Citas Programadas,3,6,23,43,43,36,57,107,83,71,...,85,78,83,140,101,26,NaN,0.269102,0.249979,0.204878
Citas Efectivas,2,5,5,23,19,14,18,27,33,18,...,43,36,59,103,53,15,NaN,NaN,NaN,NaN
Ventas,NaN,1,NaN,NaN,1,2,NaN,6,1,5,...,13,11,8,9,7,1,NaN,Cota (Ventas) Ultimo Semestre,NaN,NaN
Conversion,0,0.006897,0,0,0.002857,0.010417,0,0.004435,0.000876,0.00591,...,0.020472,0.011224,0.009592,0.013493,0.009358,0.003356,NaN,Minima,Optima,Maxima
Aporte,NaN,0.083333,0,0,0.076923,0.333333,0,0.352941,0.058824,0.217391,...,0.342105,0.366667,0.195122,0.219512,0.2,0.027027,NaN,6.392319,9,11.607681

In [145]:
#Transponer la tabla
digital = digital.T.reset_index()

digital

,Digital,Leads,Efectivos,SDC,PDM,Citas Programadas,Citas Efectivas,Ventas,Conversion,Aporte
0,"Febrero, 24",57,NaN,-,-,3,2,NaN,0,NaN
1,"Marzo, 24",145,NaN,-,-,6,5,1,0.006897,0.083333
2,"Abril, 24",129,NaN,-,-,23,5,NaN,0,0
3,"Mayo, 24",463,NaN,-,-,43,23,NaN,0,0
4,"Junio, 24",350,NaN,-,-,43,19,1,0.002857,0.076923
5,"Julio, 24",192,NaN,-,-,36,14,2,0.010417,0.333333
6,"Agosto, 24",1112,NaN,-,-,57,18,NaN,0,0
7,"Septiembre, 24",1353,NaN,-,8,107,27,6,0.004435,0.352941
8,"Octubre, 24",1142,NaN,-,7,83,33,1,0.000876,0.058824
9,"Noviembre, 24",846,NaN,-,17,71,18,5,0.00591,0.217391
10,"Diciembre, 24",755,NaN,-,28,50,27,10,0.013245,0.454545
11,"Enero, 25",202,NaN,21,22,74,37,9,0.044554,0.28125
12,"Febrero, 25",207,NaN,28,24,45,30,4,0.019324,0.153846
13,"Marzo, 25",491,NaN,13,16,25,19,12,0.02444,0.6
14,"Abril, 25",749,NaN,6,17,47,33,5,0.006676,0.166667
15,"Mayo, 25",361,NaN,15,26,37,32,9,0.024931,0.3
16,"Junio, 25",576,NaN,19,21,69,34,12,0.020833,0.352941
17,"Julio, 25",699,NaN,29,33,89,45,9,0.012876,0.225
18,"Agosto, 25",827,239,29,31,135,51,9,0.010883,0.25
19,"Septiembre, 25",676,344,36,31,125,73,15,0.022189,0.555556
20,"Octubre, 25",688,329,50,32,110,60,10,0.014535,0.263158
21,"Noviembre, 25",554,342,42,22,97,55,14,0.025271,0.35
22,"Diciembre, 25",908,594,39,23,90,51,8,0.008811,0.235294
23,"Enero, 26",922,674,23,22,110,56,6,0.006508,0.176471
24,"Febrero, 26",635,457,21,22,85,43,13,0.020472,0.342105
25,"Marzo, 26",980,618,16,25,78,36,11,0.011224,0.366667
26,"Abril, 26",834,179,32,35,83,59,8,0.009592,0.195122
27,"Mayo, 26",667,170,30,35,140,103,9,0.013493,0.219512
28,"Junio, 26",748,200,28,28,101,53,7,0.009358,0.2
29,"Julio,26",298,64,3,12,26,15,1,0.003356,0.027027
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Historica,0.013748,NaN,Aporte,Historica,0.269102,NaN,Cota (Ventas) Ultimo Semestre,Minima,6.392319
32,Año actual,0.011775,NaN,NaN,Año actual,0.249979,NaN,NaN,Optima,9
33,Ultimos 3 meses,0.010815,NaN,NaN,Ultimos 3 meses,0.204878,NaN,NaN,Maxima,11.607681

In [146]:
#Cambiar nombre de la primera columna
digital = digital.rename(columns={digital.columns[0]: "Mes"})

#Quitar el nombre que quedó arriba
digital.columns.name = None

digital.head()

,Mes,Leads,Efectivos,SDC,PDM,Citas Programadas,Citas Efectivas,Ventas,Conversion,Aporte
0,"Febrero, 24",57,NaN,-,-,3,2,NaN,0,NaN
1,"Marzo, 24",145,NaN,-,-,6,5,1,0.006897,0.083333
2,"Abril, 24",129,NaN,-,-,23,5,NaN,0,0
3,"Mayo, 24",463,NaN,-,-,43,23,NaN,0,0
4,"Junio, 24",350,NaN,-,-,43,19,1,0.002857,0.076923

In [147]:
#Reemplazar guiones por valores nulos
digital = digital.replace("-", np.nan)

In [148]:
#Contar valores nulos por columna
digital.isnull().sum()

Mes                   1
Leads                 1
Efectivos            22
SDC                  14
PDM                   8
Citas Programadas     1
Citas Efectivas       4
Ventas                7
Conversion            1
Aporte                2
dtype: int64

In [149]:
#Reemplazar valores nulos por 0
digital = digital.fillna(0)

In [150]:
#Contar valores nulos por columna
digital.isnull().sum()

Mes                  0
Leads                0
Efectivos            0
SDC                  0
PDM                  0
Citas Programadas    0
Citas Efectivas      0
Ventas               0
Conversion           0
Aporte               0
dtype: int64

In [151]:
#Guardar las bases limpias en un archivo Excel
with pd.ExcelWriter("Principales_Canales_Limpio.xlsx") as writer:
    piso.to_excel(writer, sheet_name="Piso", index=False)
    plazas.to_excel(writer, sheet_name="Plazas", index=False)
    digital.to_excel(writer, sheet_name="Digital", index=False)